version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  node: circleci/node@2

jobs:
  build: 
    docker:
      - image: cimg/ruby:2.7.5-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: rubocop
          command: |
            bundle exec rubocop

  test: 
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.5-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
      - image: circleci/postgres:9.5-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
        environment: 
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: db/shop_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Run RSpec
          command: bundle exec rspec
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/rspec

workflows:
  version: 2
  build_and_test:     
    jobs:             
      - build         
      - test:         
          requires:   
            - build   
